//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRollApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        public int UserId { get; set; }
        public int WeekId { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> SunHours { get; set; }
        public Nullable<int> MonHours { get; set; }
        public Nullable<int> TuesHours { get; set; }
        public Nullable<int> WedsHours { get; set; }
        public Nullable<int> ThursHours { get; set; }
        public Nullable<int> FriHours { get; set; }
        public Nullable<int> SatHours { get; set; }
        public string status { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
